version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: nextcloud_db
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    networks:
      - nextcloud_network
    volumes:
      - nextcloud_db:/var/lib/mysql

  nextcloud:
    image: nextcloud:25
    container_name: nextcloud_app
    restart: always
    env_file: .env
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - nextcloud_network
    volumes:
      - nextcloud_data:/var/www/html
    ports:
      - 127.0.0.1:9721:80

  collabora:
    image: collabora/code:24.04.9.2.1
    container_name: nextcloud_collabora
    env_file: .env
    cap_add:
      - MKNOD
    restart: always
    # 
    # I needed extra_hosts because collabora container kept resolving
    # Nextcloud's public domain name to localhost.
    #
    # extra_hosts:
    #   - "nextcloud.example.com:1.2.3.4"
    environment:
      - domain=${COLLABORA_NEXTCLOUD_DOMAIN}
      - server_name=${COLLABORA_OWN_DOMAIN}
      - username=${COLLABORA_ADMIN_USERNAME}
      - password=${COLLABORA_ADMIN_PASSWORD}
    ports:
      - 127.0.0.1:9722:9980
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./coolwsd.xml:/etc/coolwsd/coolwsd.xml
    networks:
      - nextcloud_network

volumes:
  nextcloud_db:
    name: nextcloud_db
  nextcloud_data:
    name: nextcloud_data

networks:
  nextcloud_network:
    name: nextcloud_network
